/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "backendmonitor_constants.h"

namespace openstars { namespace base { namespace storage { namespace monitor {

const backendmonitorConstants g_backendmonitor_constants;

backendmonitorConstants::backendmonitorConstants() {
}

}}}} // namespace

