/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef backendmonitor_CONSTANTS_H
#define backendmonitor_CONSTANTS_H

#include "backendmonitor_types.h"

namespace openstars { namespace base { namespace storage { namespace monitor {

class backendmonitorConstants {
 public:
  backendmonitorConstants();

};

extern const backendmonitorConstants g_backendmonitor_constants;

}}}} // namespace

#endif
