/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "distributed_constants.h"

namespace openstars { namespace distributed {

const distributedConstants g_distributed_constants;

distributedConstants::distributedConstants() {
}

}} // namespace

