// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MonitorReadService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::openstars::base::monitor;

class MonitorReadServiceHandler : virtual public MonitorReadServiceIf {
 public:
  MonitorReadServiceHandler() {
    // Your initialization goes here
  }

  void getCurrentStat(systemStat& _return) {
    // Your implementation goes here
    printf("getCurrentStat\n");
  }

  void getStat(systemStat& _return, const int32_t seconds) {
    // Your implementation goes here
    printf("getStat\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MonitorReadServiceHandler> handler(new MonitorReadServiceHandler());
  shared_ptr<TProcessor> processor(new MonitorReadServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

