/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "monitor_constants.h"

namespace openstars { namespace base { namespace monitor {

const monitorConstants g_monitor_constants;

monitorConstants::monitorConstants() {
}

}}} // namespace

