/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef OpenBaseService_H
#define OpenBaseService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "openbase_types.h"

namespace openstars { namespace base {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

/**
 * Standard base service
 */
class OpenBaseServiceIf {
 public:
  virtual ~OpenBaseServiceIf() {}

  /**
   * Returns a descriptive name of the service
   */
  virtual void getName(std::string& _return) = 0;

  /**
   * Returns the version of the service
   */
  virtual void getVersion(std::string& _return) = 0;

  /**
   * Gets the status of this service
   */
  virtual service_status::type getStatus() = 0;

  /**
   * User friendly description of status, such as why the service is in
   * the dead or warning state, or what is being started or stopped.
   */
  virtual void getStatusDetails(std::string& _return) = 0;

  /**
   * Gets the counters for this service
   */
  virtual void getCounters(std::map<std::string, int64_t> & _return) = 0;

  /**
   * Gets the value of a single counter
   * 
   * @param key
   */
  virtual int64_t getCounter(const std::string& key) = 0;

  /**
   * Sets an option
   * 
   * @param key
   * @param value
   */
  virtual void setOption(const std::string& key, const std::string& value) = 0;

  /**
   * Gets an option
   * 
   * @param key
   */
  virtual void getOption(std::string& _return, const std::string& key) = 0;

  /**
   * Gets all options
   */
  virtual void getOptions(std::map<std::string, std::string> & _return) = 0;

  /**
   * Returns a CPU profile over the given time interval (client and server
   * must agree on the profile format).
   * 
   * @param profileDurationInSec
   */
  virtual void getCpuProfile(std::string& _return, const int32_t profileDurationInSec) = 0;

  /**
   * Returns the unix time that the server has been running since
   */
  virtual int64_t aliveSince() = 0;

  /**
   * Tell the server to reload its configuration, reopen log files, etc
   */
  virtual void reinitialize() = 0;

  /**
   * Suggest a shutdown to the server
   */
  virtual void shutdown() = 0;
};

class OpenBaseServiceIfFactory {
 public:
  typedef OpenBaseServiceIf Handler;

  virtual ~OpenBaseServiceIfFactory() {}

  virtual OpenBaseServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(OpenBaseServiceIf* /* handler */) = 0;
  };

class OpenBaseServiceIfSingletonFactory : virtual public OpenBaseServiceIfFactory {
 public:
  OpenBaseServiceIfSingletonFactory(const ::std::shared_ptr<OpenBaseServiceIf>& iface) : iface_(iface) {}
  virtual ~OpenBaseServiceIfSingletonFactory() {}

  virtual OpenBaseServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(OpenBaseServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<OpenBaseServiceIf> iface_;
};

class OpenBaseServiceNull : virtual public OpenBaseServiceIf {
 public:
  virtual ~OpenBaseServiceNull() {}
  void getName(std::string& /* _return */) override {
    return;
  }
  void getVersion(std::string& /* _return */) override {
    return;
  }
  service_status::type getStatus() override {
    service_status::type _return = static_cast<service_status::type>(0);
    return _return;
  }
  void getStatusDetails(std::string& /* _return */) override {
    return;
  }
  void getCounters(std::map<std::string, int64_t> & /* _return */) override {
    return;
  }
  int64_t getCounter(const std::string& /* key */) override {
    int64_t _return = 0;
    return _return;
  }
  void setOption(const std::string& /* key */, const std::string& /* value */) override {
    return;
  }
  void getOption(std::string& /* _return */, const std::string& /* key */) override {
    return;
  }
  void getOptions(std::map<std::string, std::string> & /* _return */) override {
    return;
  }
  void getCpuProfile(std::string& /* _return */, const int32_t /* profileDurationInSec */) override {
    return;
  }
  int64_t aliveSince() override {
    int64_t _return = 0;
    return _return;
  }
  void reinitialize() override {
    return;
  }
  void shutdown() override {
    return;
  }
};


class OpenBaseService_getName_args {
 public:

  OpenBaseService_getName_args(const OpenBaseService_getName_args&) noexcept;
  OpenBaseService_getName_args& operator=(const OpenBaseService_getName_args&) noexcept;
  OpenBaseService_getName_args() noexcept {
  }

  virtual ~OpenBaseService_getName_args() noexcept;

  bool operator == (const OpenBaseService_getName_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const OpenBaseService_getName_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getName_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_getName_pargs {
 public:


  virtual ~OpenBaseService_getName_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getName_result__isset {
  _OpenBaseService_getName_result__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getName_result__isset;

class OpenBaseService_getName_result {
 public:

  OpenBaseService_getName_result(const OpenBaseService_getName_result&);
  OpenBaseService_getName_result& operator=(const OpenBaseService_getName_result&);
  OpenBaseService_getName_result() noexcept
                                 : success() {
  }

  virtual ~OpenBaseService_getName_result() noexcept;
  std::string success;

  _OpenBaseService_getName_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const OpenBaseService_getName_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getName_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getName_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getName_presult__isset {
  _OpenBaseService_getName_presult__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getName_presult__isset;

class OpenBaseService_getName_presult {
 public:


  virtual ~OpenBaseService_getName_presult() noexcept;
  std::string* success;

  _OpenBaseService_getName_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class OpenBaseService_getVersion_args {
 public:

  OpenBaseService_getVersion_args(const OpenBaseService_getVersion_args&) noexcept;
  OpenBaseService_getVersion_args& operator=(const OpenBaseService_getVersion_args&) noexcept;
  OpenBaseService_getVersion_args() noexcept {
  }

  virtual ~OpenBaseService_getVersion_args() noexcept;

  bool operator == (const OpenBaseService_getVersion_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const OpenBaseService_getVersion_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getVersion_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_getVersion_pargs {
 public:


  virtual ~OpenBaseService_getVersion_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getVersion_result__isset {
  _OpenBaseService_getVersion_result__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getVersion_result__isset;

class OpenBaseService_getVersion_result {
 public:

  OpenBaseService_getVersion_result(const OpenBaseService_getVersion_result&);
  OpenBaseService_getVersion_result& operator=(const OpenBaseService_getVersion_result&);
  OpenBaseService_getVersion_result() noexcept
                                    : success() {
  }

  virtual ~OpenBaseService_getVersion_result() noexcept;
  std::string success;

  _OpenBaseService_getVersion_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const OpenBaseService_getVersion_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getVersion_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getVersion_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getVersion_presult__isset {
  _OpenBaseService_getVersion_presult__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getVersion_presult__isset;

class OpenBaseService_getVersion_presult {
 public:


  virtual ~OpenBaseService_getVersion_presult() noexcept;
  std::string* success;

  _OpenBaseService_getVersion_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class OpenBaseService_getStatus_args {
 public:

  OpenBaseService_getStatus_args(const OpenBaseService_getStatus_args&) noexcept;
  OpenBaseService_getStatus_args& operator=(const OpenBaseService_getStatus_args&) noexcept;
  OpenBaseService_getStatus_args() noexcept {
  }

  virtual ~OpenBaseService_getStatus_args() noexcept;

  bool operator == (const OpenBaseService_getStatus_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const OpenBaseService_getStatus_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getStatus_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_getStatus_pargs {
 public:


  virtual ~OpenBaseService_getStatus_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getStatus_result__isset {
  _OpenBaseService_getStatus_result__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getStatus_result__isset;

class OpenBaseService_getStatus_result {
 public:

  OpenBaseService_getStatus_result(const OpenBaseService_getStatus_result&) noexcept;
  OpenBaseService_getStatus_result& operator=(const OpenBaseService_getStatus_result&) noexcept;
  OpenBaseService_getStatus_result() noexcept
                                   : success(static_cast<service_status::type>(0)) {
  }

  virtual ~OpenBaseService_getStatus_result() noexcept;
  /**
   * 
   * @see service_status
   */
  service_status::type success;

  _OpenBaseService_getStatus_result__isset __isset;

  void __set_success(const service_status::type val);

  bool operator == (const OpenBaseService_getStatus_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getStatus_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getStatus_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getStatus_presult__isset {
  _OpenBaseService_getStatus_presult__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getStatus_presult__isset;

class OpenBaseService_getStatus_presult {
 public:


  virtual ~OpenBaseService_getStatus_presult() noexcept;
  /**
   * 
   * @see service_status
   */
  service_status::type* success;

  _OpenBaseService_getStatus_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class OpenBaseService_getStatusDetails_args {
 public:

  OpenBaseService_getStatusDetails_args(const OpenBaseService_getStatusDetails_args&) noexcept;
  OpenBaseService_getStatusDetails_args& operator=(const OpenBaseService_getStatusDetails_args&) noexcept;
  OpenBaseService_getStatusDetails_args() noexcept {
  }

  virtual ~OpenBaseService_getStatusDetails_args() noexcept;

  bool operator == (const OpenBaseService_getStatusDetails_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const OpenBaseService_getStatusDetails_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getStatusDetails_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_getStatusDetails_pargs {
 public:


  virtual ~OpenBaseService_getStatusDetails_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getStatusDetails_result__isset {
  _OpenBaseService_getStatusDetails_result__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getStatusDetails_result__isset;

class OpenBaseService_getStatusDetails_result {
 public:

  OpenBaseService_getStatusDetails_result(const OpenBaseService_getStatusDetails_result&);
  OpenBaseService_getStatusDetails_result& operator=(const OpenBaseService_getStatusDetails_result&);
  OpenBaseService_getStatusDetails_result() noexcept
                                          : success() {
  }

  virtual ~OpenBaseService_getStatusDetails_result() noexcept;
  std::string success;

  _OpenBaseService_getStatusDetails_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const OpenBaseService_getStatusDetails_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getStatusDetails_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getStatusDetails_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getStatusDetails_presult__isset {
  _OpenBaseService_getStatusDetails_presult__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getStatusDetails_presult__isset;

class OpenBaseService_getStatusDetails_presult {
 public:


  virtual ~OpenBaseService_getStatusDetails_presult() noexcept;
  std::string* success;

  _OpenBaseService_getStatusDetails_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class OpenBaseService_getCounters_args {
 public:

  OpenBaseService_getCounters_args(const OpenBaseService_getCounters_args&) noexcept;
  OpenBaseService_getCounters_args& operator=(const OpenBaseService_getCounters_args&) noexcept;
  OpenBaseService_getCounters_args() noexcept {
  }

  virtual ~OpenBaseService_getCounters_args() noexcept;

  bool operator == (const OpenBaseService_getCounters_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const OpenBaseService_getCounters_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getCounters_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_getCounters_pargs {
 public:


  virtual ~OpenBaseService_getCounters_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getCounters_result__isset {
  _OpenBaseService_getCounters_result__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getCounters_result__isset;

class OpenBaseService_getCounters_result {
 public:

  OpenBaseService_getCounters_result(const OpenBaseService_getCounters_result&);
  OpenBaseService_getCounters_result& operator=(const OpenBaseService_getCounters_result&);
  OpenBaseService_getCounters_result() noexcept {
  }

  virtual ~OpenBaseService_getCounters_result() noexcept;
  std::map<std::string, int64_t>  success;

  _OpenBaseService_getCounters_result__isset __isset;

  void __set_success(const std::map<std::string, int64_t> & val);

  bool operator == (const OpenBaseService_getCounters_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getCounters_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getCounters_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getCounters_presult__isset {
  _OpenBaseService_getCounters_presult__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getCounters_presult__isset;

class OpenBaseService_getCounters_presult {
 public:


  virtual ~OpenBaseService_getCounters_presult() noexcept;
  std::map<std::string, int64_t> * success;

  _OpenBaseService_getCounters_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _OpenBaseService_getCounter_args__isset {
  _OpenBaseService_getCounter_args__isset() : key(false) {}
  bool key :1;
} _OpenBaseService_getCounter_args__isset;

class OpenBaseService_getCounter_args {
 public:

  OpenBaseService_getCounter_args(const OpenBaseService_getCounter_args&);
  OpenBaseService_getCounter_args& operator=(const OpenBaseService_getCounter_args&);
  OpenBaseService_getCounter_args() noexcept
                                  : key() {
  }

  virtual ~OpenBaseService_getCounter_args() noexcept;
  std::string key;

  _OpenBaseService_getCounter_args__isset __isset;

  void __set_key(const std::string& val);

  bool operator == (const OpenBaseService_getCounter_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getCounter_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getCounter_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_getCounter_pargs {
 public:


  virtual ~OpenBaseService_getCounter_pargs() noexcept;
  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getCounter_result__isset {
  _OpenBaseService_getCounter_result__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getCounter_result__isset;

class OpenBaseService_getCounter_result {
 public:

  OpenBaseService_getCounter_result(const OpenBaseService_getCounter_result&) noexcept;
  OpenBaseService_getCounter_result& operator=(const OpenBaseService_getCounter_result&) noexcept;
  OpenBaseService_getCounter_result() noexcept
                                    : success(0) {
  }

  virtual ~OpenBaseService_getCounter_result() noexcept;
  int64_t success;

  _OpenBaseService_getCounter_result__isset __isset;

  void __set_success(const int64_t val);

  bool operator == (const OpenBaseService_getCounter_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getCounter_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getCounter_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getCounter_presult__isset {
  _OpenBaseService_getCounter_presult__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getCounter_presult__isset;

class OpenBaseService_getCounter_presult {
 public:


  virtual ~OpenBaseService_getCounter_presult() noexcept;
  int64_t* success;

  _OpenBaseService_getCounter_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _OpenBaseService_setOption_args__isset {
  _OpenBaseService_setOption_args__isset() : key(false), value(false) {}
  bool key :1;
  bool value :1;
} _OpenBaseService_setOption_args__isset;

class OpenBaseService_setOption_args {
 public:

  OpenBaseService_setOption_args(const OpenBaseService_setOption_args&);
  OpenBaseService_setOption_args& operator=(const OpenBaseService_setOption_args&);
  OpenBaseService_setOption_args() noexcept
                                 : key(),
                                   value() {
  }

  virtual ~OpenBaseService_setOption_args() noexcept;
  std::string key;
  std::string value;

  _OpenBaseService_setOption_args__isset __isset;

  void __set_key(const std::string& val);

  void __set_value(const std::string& val);

  bool operator == (const OpenBaseService_setOption_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_setOption_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_setOption_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_setOption_pargs {
 public:


  virtual ~OpenBaseService_setOption_pargs() noexcept;
  const std::string* key;
  const std::string* value;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_setOption_result {
 public:

  OpenBaseService_setOption_result(const OpenBaseService_setOption_result&) noexcept;
  OpenBaseService_setOption_result& operator=(const OpenBaseService_setOption_result&) noexcept;
  OpenBaseService_setOption_result() noexcept {
  }

  virtual ~OpenBaseService_setOption_result() noexcept;

  bool operator == (const OpenBaseService_setOption_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const OpenBaseService_setOption_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_setOption_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_setOption_presult {
 public:


  virtual ~OpenBaseService_setOption_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _OpenBaseService_getOption_args__isset {
  _OpenBaseService_getOption_args__isset() : key(false) {}
  bool key :1;
} _OpenBaseService_getOption_args__isset;

class OpenBaseService_getOption_args {
 public:

  OpenBaseService_getOption_args(const OpenBaseService_getOption_args&);
  OpenBaseService_getOption_args& operator=(const OpenBaseService_getOption_args&);
  OpenBaseService_getOption_args() noexcept
                                 : key() {
  }

  virtual ~OpenBaseService_getOption_args() noexcept;
  std::string key;

  _OpenBaseService_getOption_args__isset __isset;

  void __set_key(const std::string& val);

  bool operator == (const OpenBaseService_getOption_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getOption_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getOption_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_getOption_pargs {
 public:


  virtual ~OpenBaseService_getOption_pargs() noexcept;
  const std::string* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getOption_result__isset {
  _OpenBaseService_getOption_result__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getOption_result__isset;

class OpenBaseService_getOption_result {
 public:

  OpenBaseService_getOption_result(const OpenBaseService_getOption_result&);
  OpenBaseService_getOption_result& operator=(const OpenBaseService_getOption_result&);
  OpenBaseService_getOption_result() noexcept
                                   : success() {
  }

  virtual ~OpenBaseService_getOption_result() noexcept;
  std::string success;

  _OpenBaseService_getOption_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const OpenBaseService_getOption_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getOption_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getOption_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getOption_presult__isset {
  _OpenBaseService_getOption_presult__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getOption_presult__isset;

class OpenBaseService_getOption_presult {
 public:


  virtual ~OpenBaseService_getOption_presult() noexcept;
  std::string* success;

  _OpenBaseService_getOption_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class OpenBaseService_getOptions_args {
 public:

  OpenBaseService_getOptions_args(const OpenBaseService_getOptions_args&) noexcept;
  OpenBaseService_getOptions_args& operator=(const OpenBaseService_getOptions_args&) noexcept;
  OpenBaseService_getOptions_args() noexcept {
  }

  virtual ~OpenBaseService_getOptions_args() noexcept;

  bool operator == (const OpenBaseService_getOptions_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const OpenBaseService_getOptions_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getOptions_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_getOptions_pargs {
 public:


  virtual ~OpenBaseService_getOptions_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getOptions_result__isset {
  _OpenBaseService_getOptions_result__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getOptions_result__isset;

class OpenBaseService_getOptions_result {
 public:

  OpenBaseService_getOptions_result(const OpenBaseService_getOptions_result&);
  OpenBaseService_getOptions_result& operator=(const OpenBaseService_getOptions_result&);
  OpenBaseService_getOptions_result() noexcept {
  }

  virtual ~OpenBaseService_getOptions_result() noexcept;
  std::map<std::string, std::string>  success;

  _OpenBaseService_getOptions_result__isset __isset;

  void __set_success(const std::map<std::string, std::string> & val);

  bool operator == (const OpenBaseService_getOptions_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getOptions_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getOptions_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getOptions_presult__isset {
  _OpenBaseService_getOptions_presult__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getOptions_presult__isset;

class OpenBaseService_getOptions_presult {
 public:


  virtual ~OpenBaseService_getOptions_presult() noexcept;
  std::map<std::string, std::string> * success;

  _OpenBaseService_getOptions_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _OpenBaseService_getCpuProfile_args__isset {
  _OpenBaseService_getCpuProfile_args__isset() : profileDurationInSec(false) {}
  bool profileDurationInSec :1;
} _OpenBaseService_getCpuProfile_args__isset;

class OpenBaseService_getCpuProfile_args {
 public:

  OpenBaseService_getCpuProfile_args(const OpenBaseService_getCpuProfile_args&) noexcept;
  OpenBaseService_getCpuProfile_args& operator=(const OpenBaseService_getCpuProfile_args&) noexcept;
  OpenBaseService_getCpuProfile_args() noexcept
                                     : profileDurationInSec(0) {
  }

  virtual ~OpenBaseService_getCpuProfile_args() noexcept;
  int32_t profileDurationInSec;

  _OpenBaseService_getCpuProfile_args__isset __isset;

  void __set_profileDurationInSec(const int32_t val);

  bool operator == (const OpenBaseService_getCpuProfile_args & rhs) const
  {
    if (!(profileDurationInSec == rhs.profileDurationInSec))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getCpuProfile_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getCpuProfile_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_getCpuProfile_pargs {
 public:


  virtual ~OpenBaseService_getCpuProfile_pargs() noexcept;
  const int32_t* profileDurationInSec;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getCpuProfile_result__isset {
  _OpenBaseService_getCpuProfile_result__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getCpuProfile_result__isset;

class OpenBaseService_getCpuProfile_result {
 public:

  OpenBaseService_getCpuProfile_result(const OpenBaseService_getCpuProfile_result&);
  OpenBaseService_getCpuProfile_result& operator=(const OpenBaseService_getCpuProfile_result&);
  OpenBaseService_getCpuProfile_result() noexcept
                                       : success() {
  }

  virtual ~OpenBaseService_getCpuProfile_result() noexcept;
  std::string success;

  _OpenBaseService_getCpuProfile_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const OpenBaseService_getCpuProfile_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_getCpuProfile_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_getCpuProfile_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_getCpuProfile_presult__isset {
  _OpenBaseService_getCpuProfile_presult__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_getCpuProfile_presult__isset;

class OpenBaseService_getCpuProfile_presult {
 public:


  virtual ~OpenBaseService_getCpuProfile_presult() noexcept;
  std::string* success;

  _OpenBaseService_getCpuProfile_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class OpenBaseService_aliveSince_args {
 public:

  OpenBaseService_aliveSince_args(const OpenBaseService_aliveSince_args&) noexcept;
  OpenBaseService_aliveSince_args& operator=(const OpenBaseService_aliveSince_args&) noexcept;
  OpenBaseService_aliveSince_args() noexcept {
  }

  virtual ~OpenBaseService_aliveSince_args() noexcept;

  bool operator == (const OpenBaseService_aliveSince_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const OpenBaseService_aliveSince_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_aliveSince_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_aliveSince_pargs {
 public:


  virtual ~OpenBaseService_aliveSince_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_aliveSince_result__isset {
  _OpenBaseService_aliveSince_result__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_aliveSince_result__isset;

class OpenBaseService_aliveSince_result {
 public:

  OpenBaseService_aliveSince_result(const OpenBaseService_aliveSince_result&) noexcept;
  OpenBaseService_aliveSince_result& operator=(const OpenBaseService_aliveSince_result&) noexcept;
  OpenBaseService_aliveSince_result() noexcept
                                    : success(0) {
  }

  virtual ~OpenBaseService_aliveSince_result() noexcept;
  int64_t success;

  _OpenBaseService_aliveSince_result__isset __isset;

  void __set_success(const int64_t val);

  bool operator == (const OpenBaseService_aliveSince_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const OpenBaseService_aliveSince_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_aliveSince_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _OpenBaseService_aliveSince_presult__isset {
  _OpenBaseService_aliveSince_presult__isset() : success(false) {}
  bool success :1;
} _OpenBaseService_aliveSince_presult__isset;

class OpenBaseService_aliveSince_presult {
 public:


  virtual ~OpenBaseService_aliveSince_presult() noexcept;
  int64_t* success;

  _OpenBaseService_aliveSince_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class OpenBaseService_reinitialize_args {
 public:

  OpenBaseService_reinitialize_args(const OpenBaseService_reinitialize_args&) noexcept;
  OpenBaseService_reinitialize_args& operator=(const OpenBaseService_reinitialize_args&) noexcept;
  OpenBaseService_reinitialize_args() noexcept {
  }

  virtual ~OpenBaseService_reinitialize_args() noexcept;

  bool operator == (const OpenBaseService_reinitialize_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const OpenBaseService_reinitialize_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_reinitialize_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_reinitialize_pargs {
 public:


  virtual ~OpenBaseService_reinitialize_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_shutdown_args {
 public:

  OpenBaseService_shutdown_args(const OpenBaseService_shutdown_args&) noexcept;
  OpenBaseService_shutdown_args& operator=(const OpenBaseService_shutdown_args&) noexcept;
  OpenBaseService_shutdown_args() noexcept {
  }

  virtual ~OpenBaseService_shutdown_args() noexcept;

  bool operator == (const OpenBaseService_shutdown_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const OpenBaseService_shutdown_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OpenBaseService_shutdown_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class OpenBaseService_shutdown_pargs {
 public:


  virtual ~OpenBaseService_shutdown_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class OpenBaseServiceClient : virtual public OpenBaseServiceIf {
 public:
  OpenBaseServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  OpenBaseServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * Returns a descriptive name of the service
   */
  void getName(std::string& _return) override;
  void send_getName();
  void recv_getName(std::string& _return);
  /**
   * Returns the version of the service
   */
  void getVersion(std::string& _return) override;
  void send_getVersion();
  void recv_getVersion(std::string& _return);
  /**
   * Gets the status of this service
   */
  service_status::type getStatus() override;
  void send_getStatus();
  service_status::type recv_getStatus();
  /**
   * User friendly description of status, such as why the service is in
   * the dead or warning state, or what is being started or stopped.
   */
  void getStatusDetails(std::string& _return) override;
  void send_getStatusDetails();
  void recv_getStatusDetails(std::string& _return);
  /**
   * Gets the counters for this service
   */
  void getCounters(std::map<std::string, int64_t> & _return) override;
  void send_getCounters();
  void recv_getCounters(std::map<std::string, int64_t> & _return);
  /**
   * Gets the value of a single counter
   * 
   * @param key
   */
  int64_t getCounter(const std::string& key) override;
  void send_getCounter(const std::string& key);
  int64_t recv_getCounter();
  /**
   * Sets an option
   * 
   * @param key
   * @param value
   */
  void setOption(const std::string& key, const std::string& value) override;
  void send_setOption(const std::string& key, const std::string& value);
  void recv_setOption();
  /**
   * Gets an option
   * 
   * @param key
   */
  void getOption(std::string& _return, const std::string& key) override;
  void send_getOption(const std::string& key);
  void recv_getOption(std::string& _return);
  /**
   * Gets all options
   */
  void getOptions(std::map<std::string, std::string> & _return) override;
  void send_getOptions();
  void recv_getOptions(std::map<std::string, std::string> & _return);
  /**
   * Returns a CPU profile over the given time interval (client and server
   * must agree on the profile format).
   * 
   * @param profileDurationInSec
   */
  void getCpuProfile(std::string& _return, const int32_t profileDurationInSec) override;
  void send_getCpuProfile(const int32_t profileDurationInSec);
  void recv_getCpuProfile(std::string& _return);
  /**
   * Returns the unix time that the server has been running since
   */
  int64_t aliveSince() override;
  void send_aliveSince();
  int64_t recv_aliveSince();
  /**
   * Tell the server to reload its configuration, reopen log files, etc
   */
  void reinitialize() override;
  void send_reinitialize();
  /**
   * Suggest a shutdown to the server
   */
  void shutdown() override;
  void send_shutdown();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class OpenBaseServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<OpenBaseServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (OpenBaseServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getName(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getVersion(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getStatus(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getStatusDetails(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getCounters(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getCounter(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_setOption(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getOption(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getOptions(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getCpuProfile(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_aliveSince(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_reinitialize(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_shutdown(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  OpenBaseServiceProcessor(::std::shared_ptr<OpenBaseServiceIf> iface) :
    iface_(iface) {
    processMap_["getName"] = &OpenBaseServiceProcessor::process_getName;
    processMap_["getVersion"] = &OpenBaseServiceProcessor::process_getVersion;
    processMap_["getStatus"] = &OpenBaseServiceProcessor::process_getStatus;
    processMap_["getStatusDetails"] = &OpenBaseServiceProcessor::process_getStatusDetails;
    processMap_["getCounters"] = &OpenBaseServiceProcessor::process_getCounters;
    processMap_["getCounter"] = &OpenBaseServiceProcessor::process_getCounter;
    processMap_["setOption"] = &OpenBaseServiceProcessor::process_setOption;
    processMap_["getOption"] = &OpenBaseServiceProcessor::process_getOption;
    processMap_["getOptions"] = &OpenBaseServiceProcessor::process_getOptions;
    processMap_["getCpuProfile"] = &OpenBaseServiceProcessor::process_getCpuProfile;
    processMap_["aliveSince"] = &OpenBaseServiceProcessor::process_aliveSince;
    processMap_["reinitialize"] = &OpenBaseServiceProcessor::process_reinitialize;
    processMap_["shutdown"] = &OpenBaseServiceProcessor::process_shutdown;
  }

  virtual ~OpenBaseServiceProcessor() {}
};

class OpenBaseServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  OpenBaseServiceProcessorFactory(const ::std::shared_ptr< OpenBaseServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< OpenBaseServiceIfFactory > handlerFactory_;
};

class OpenBaseServiceMultiface : virtual public OpenBaseServiceIf {
 public:
  OpenBaseServiceMultiface(std::vector<std::shared_ptr<OpenBaseServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~OpenBaseServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<OpenBaseServiceIf> > ifaces_;
  OpenBaseServiceMultiface() {}
  void add(::std::shared_ptr<OpenBaseServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  /**
   * Returns a descriptive name of the service
   */
  void getName(std::string& _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getName(_return);
    }
    ifaces_[i]->getName(_return);
    return;
  }

  /**
   * Returns the version of the service
   */
  void getVersion(std::string& _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getVersion(_return);
    }
    ifaces_[i]->getVersion(_return);
    return;
  }

  /**
   * Gets the status of this service
   */
  service_status::type getStatus() override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getStatus();
    }
    return ifaces_[i]->getStatus();
  }

  /**
   * User friendly description of status, such as why the service is in
   * the dead or warning state, or what is being started or stopped.
   */
  void getStatusDetails(std::string& _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getStatusDetails(_return);
    }
    ifaces_[i]->getStatusDetails(_return);
    return;
  }

  /**
   * Gets the counters for this service
   */
  void getCounters(std::map<std::string, int64_t> & _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getCounters(_return);
    }
    ifaces_[i]->getCounters(_return);
    return;
  }

  /**
   * Gets the value of a single counter
   * 
   * @param key
   */
  int64_t getCounter(const std::string& key) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getCounter(key);
    }
    return ifaces_[i]->getCounter(key);
  }

  /**
   * Sets an option
   * 
   * @param key
   * @param value
   */
  void setOption(const std::string& key, const std::string& value) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->setOption(key, value);
    }
    ifaces_[i]->setOption(key, value);
  }

  /**
   * Gets an option
   * 
   * @param key
   */
  void getOption(std::string& _return, const std::string& key) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getOption(_return, key);
    }
    ifaces_[i]->getOption(_return, key);
    return;
  }

  /**
   * Gets all options
   */
  void getOptions(std::map<std::string, std::string> & _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getOptions(_return);
    }
    ifaces_[i]->getOptions(_return);
    return;
  }

  /**
   * Returns a CPU profile over the given time interval (client and server
   * must agree on the profile format).
   * 
   * @param profileDurationInSec
   */
  void getCpuProfile(std::string& _return, const int32_t profileDurationInSec) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getCpuProfile(_return, profileDurationInSec);
    }
    ifaces_[i]->getCpuProfile(_return, profileDurationInSec);
    return;
  }

  /**
   * Returns the unix time that the server has been running since
   */
  int64_t aliveSince() override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->aliveSince();
    }
    return ifaces_[i]->aliveSince();
  }

  /**
   * Tell the server to reload its configuration, reopen log files, etc
   */
  void reinitialize() override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->reinitialize();
    }
    ifaces_[i]->reinitialize();
  }

  /**
   * Suggest a shutdown to the server
   */
  void shutdown() override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->shutdown();
    }
    ifaces_[i]->shutdown();
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class OpenBaseServiceConcurrentClient : virtual public OpenBaseServiceIf {
 public:
  OpenBaseServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  OpenBaseServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * Returns a descriptive name of the service
   */
  void getName(std::string& _return) override;
  int32_t send_getName();
  void recv_getName(std::string& _return, const int32_t seqid);
  /**
   * Returns the version of the service
   */
  void getVersion(std::string& _return) override;
  int32_t send_getVersion();
  void recv_getVersion(std::string& _return, const int32_t seqid);
  /**
   * Gets the status of this service
   */
  service_status::type getStatus() override;
  int32_t send_getStatus();
  service_status::type recv_getStatus(const int32_t seqid);
  /**
   * User friendly description of status, such as why the service is in
   * the dead or warning state, or what is being started or stopped.
   */
  void getStatusDetails(std::string& _return) override;
  int32_t send_getStatusDetails();
  void recv_getStatusDetails(std::string& _return, const int32_t seqid);
  /**
   * Gets the counters for this service
   */
  void getCounters(std::map<std::string, int64_t> & _return) override;
  int32_t send_getCounters();
  void recv_getCounters(std::map<std::string, int64_t> & _return, const int32_t seqid);
  /**
   * Gets the value of a single counter
   * 
   * @param key
   */
  int64_t getCounter(const std::string& key) override;
  int32_t send_getCounter(const std::string& key);
  int64_t recv_getCounter(const int32_t seqid);
  /**
   * Sets an option
   * 
   * @param key
   * @param value
   */
  void setOption(const std::string& key, const std::string& value) override;
  int32_t send_setOption(const std::string& key, const std::string& value);
  void recv_setOption(const int32_t seqid);
  /**
   * Gets an option
   * 
   * @param key
   */
  void getOption(std::string& _return, const std::string& key) override;
  int32_t send_getOption(const std::string& key);
  void recv_getOption(std::string& _return, const int32_t seqid);
  /**
   * Gets all options
   */
  void getOptions(std::map<std::string, std::string> & _return) override;
  int32_t send_getOptions();
  void recv_getOptions(std::map<std::string, std::string> & _return, const int32_t seqid);
  /**
   * Returns a CPU profile over the given time interval (client and server
   * must agree on the profile format).
   * 
   * @param profileDurationInSec
   */
  void getCpuProfile(std::string& _return, const int32_t profileDurationInSec) override;
  int32_t send_getCpuProfile(const int32_t profileDurationInSec);
  void recv_getCpuProfile(std::string& _return, const int32_t seqid);
  /**
   * Returns the unix time that the server has been running since
   */
  int64_t aliveSince() override;
  int32_t send_aliveSince();
  int64_t recv_aliveSince(const int32_t seqid);
  /**
   * Tell the server to reload its configuration, reopen log files, etc
   */
  void reinitialize() override;
  void send_reinitialize();
  /**
   * Suggest a shutdown to the server
   */
  void shutdown() override;
  void send_shutdown();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#endif
