/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef openbase_CONSTANTS_H
#define openbase_CONSTANTS_H

#include "openbase_types.h"

namespace openstars { namespace base {

class openbaseConstants {
 public:
  openbaseConstants();

};

extern const openbaseConstants g_openbase_constants;

}} // namespace

#endif
