// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TBackendManagerService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::openstars::distributed;

class TBackendManagerServiceHandler : virtual public TBackendManagerServiceIf {
 public:
  TBackendManagerServiceHandler() {
    // Your initialization goes here
  }

  void getBackends(std::vector<TBackendInfo> & _return) {
    // Your implementation goes here
    printf("getBackends\n");
  }

  void getBEWrite(std::vector<TBackendInfo> & _return, const std::string& key) {
    // Your implementation goes here
    printf("getBEWrite\n");
  }

  void getBERead(std::vector<TBackendInfo> & _return, const std::string& key) {
    // Your implementation goes here
    printf("getBERead\n");
  }

  void addBackend(const TBackendInfo& aNode) {
    // Your implementation goes here
    printf("addBackend\n");
  }

  void updateBackend(const TBackendInfo& aNode) {
    // Your implementation goes here
    printf("updateBackend\n");
  }

  void removeBackend(const TBackendInfo& aNode) {
    // Your implementation goes here
    printf("removeBackend\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<TBackendManagerServiceHandler> handler(new TBackendManagerServiceHandler());
  shared_ptr<TProcessor> processor(new TBackendManagerServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

