// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TNodeServiceBase.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::openstars::distributed;

class TNodeServiceBaseHandler : virtual public TNodeServiceBaseIf {
 public:
  TNodeServiceBaseHandler() {
    // Your initialization goes here
  }

  int32_t iPing(const int32_t value) {
    // Your implementation goes here
    printf("iPing\n");
  }

  TSyncTransactionIDType startSyncTo(const TBackendInfo& desNode) {
    // Your implementation goes here
    printf("startSyncTo\n");
  }

  void getSyncStatus(TDataMovingStatus& _return, const TSyncTransactionIDType tid) {
    // Your implementation goes here
    printf("getSyncStatus\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<TNodeServiceBaseHandler> handler(new TNodeServiceBaseHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new TNodeServiceBaseProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

